### ISSUE TITLE
Развитие либы

### ISSUE THREAD

**Issue by alewkinr** [v14dis14v/amo#1]
Привет! Нашел твой проект и хочу поконтрибьютить в него, если ты заинтересован в его развитии. На просторах гитхаба нет нормальных либ для амки на питоне,  хочется сделать годноту. Напиши мне в телеграм `@ramjet`

**Comment by v14dis14v** [comment]
Привет. Извиняюсь, что так долго не отвечал, немного занят был) Давай попробуем сделать
